### ISSUE TITLE
文字弹窗显示问题

### ISSUE THREAD

**Issue by zoulingfeng123** [chenliangloveyou/EasyShowView#1]
您好！我手动集成您这个源码，发现。EasyShowTextView  这个弹窗又问题，当配置options.textSuperViewReceiveEvent = NO;时弹窗出现在屏幕左边且有一部分没有显示，看了一下代码，好想问题出现在 EasyShowTextView.m 文件271行代码  EasyShowTextView *showView = [[EasyShowTextView alloc] initWithFrame:CGRectZero];和342行代码
if (!self.options.textSuperViewReceiveEvent) {
        showFrame.origin = CGPointMake((self.width-backGroundW)/2, showFrameY) ;
    }这里有问题，self.width的数值为0，导致显示不正常。

**Comment by chenliangloveyou** [comment]
您好，谢谢反馈，342行的self.width改成superview.width就行。已更改

**Comment by XinYangLK** [comment]
你好，东西很nice！多谢楼主分享，发现一点点小问题，在文本显示提示语 字数过多时，展示在状态栏和导航栏上的提示语会偏右，在有图片的提示语弹窗时，展示在状态栏和导航栏上的字体有展示到屏幕外现象
