### ISSUE TITLE
EasyLodingView多图播放如何使其没有透明背景框  想要的是不透明的并且全屏的背景,就像美团一样

### ISSUE THREAD

**Issue by ThatMan666** [chenliangloveyou/EasyShowView#10]

**Comment by chenliangloveyou** [comment]
把背景颜色设置为clearcolor。如下：

EasyLodingView *lodingV = [EasyLodingView showLodingText:@"3秒后能交互..." config:^EasyLodingConfig *{
                static int a = 0 ;
                int type = ++a%2 ? LodingShowTypePlayImagesLeft : LodingShowTypePlayImages ;
                return [EasyLodingConfig shared].setLodingType(type).setSuperReceiveEvent(NO).setBgColor([UIColor clearColor]);
            }];

**Comment by ThatMan666** [comment]
感谢解答  另外 好像pod search EasyShowView搜不到

**Comment by chenliangloveyou** [comment]
这个应该是cocoapods的问题，clear下本地就行。或者直接install。
