### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by niwangdaye** [chenliangloveyou/EasyShowView#14]
跳转页面  不移除空白页,返回上级,通知未移除(对EasyEmptyView是否移除抱怀疑态度),空白页,顶端提示,和自定义alert横屏适配问题!!!很适用,👍

**Comment by niwangdaye** [comment]
兄弟,我提的这个问题不算问题?

**Comment by chenliangloveyou** [comment]
通知未移除-------我这个里面应该没有通知吧。还是不太明白你说的什么意思

**Comment by libaixiao** [comment]
我在子控制器中 [EasyLodingView showLodingText:@"注册中"]，显示不了，不知道为什么！
