### ISSUE TITLE
文字提示语弹窗显示问题

### ISSUE THREAD

**Issue by XinYangLK** [chenliangloveyou/EasyShowView#2]
楼主你好，东西很nice，多谢🙏分享，不过在查看过程中发现了一点点小的问题：在纯文本提示语文字过多展示在状态栏和导航栏时，字体会偏右且顶到屏幕边缘，在带图片提示语文字过多时，展示在状态栏和导航栏时，边缘文字会被屏幕覆盖部分 测试在8p上

**Comment by chenliangloveyou** [comment]
您好，问题已解决，请更新试试！
