### ISSUE TITLE
alertView（点五次）有个弹出框

### ISSUE THREAD

**Issue by whpanda** [chenliangloveyou/EasyShowView#3]
有个提示是否删除。。。数据的弹框，没有交互按钮，就只能重新跑了

**Comment by chenliangloveyou** [comment]
您好，在appdelegate里面，初始化库的时候，加上这句话


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
    EasyShowOptions *options = [EasyShowOptions sharedEasyShowOptions];

    //  点击alertview之外的空白区域，是否销毁alertview。默认为:NO
    options.alertBgViewTapRemove = YES ;
 
    return YES ;
}

**Comment by whpanda** [comment]
好的，谢谢
