### ISSUE TITLE
iphonese问题

### ISSUE THREAD

**Issue by Guoxiafei** [chenliangloveyou/EasyShowView#4]
这个页面卡死了 iphonese
![wechatimg3](https://user-images.githubusercontent.com/16255252/34856011-da72ce62-f77d-11e7-9cbb-7186dfe21e1f.jpeg)

**Comment by chenliangloveyou** [comment]
您好，在appdelegate里面，初始化库的时候，加上这句话


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
    EasyShowOptions *options = [EasyShowOptions sharedEasyShowOptions];

    //  点击alertview之外的空白区域，是否销毁alertview。默认为:NO
    options.alertBgViewTapRemove = YES ;
 
    return YES ;
}
